#!/bin/bash
if [ $(whoami) != "root" ]; then
  echo "You need to run it with sudo"
  exit 1
fi

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cp -pf $DIR/etc/* /etc/udev/rules.d/

echo "dev config file recovered, you need to replugin your devices and restart startup service."
